server:
    port: 5556

spring:
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    application:
        name: MusicStore
    datasource:
        url: jdbc:postgresql://localhost:5432/music_store_db
        username: postgres
        password: zeovl
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        # client-id: set in IntelliJ configuration
                        # client-secret: set in IntelliJ configuration
                        redirect-uri: "{baseUrl}/auth/login/oauth2/code/{registrationId}"
                        scope:
                            - email
                            - profile
                    yandex:
                        provider: yandex
                        # client-id: set in IntelliJ configuration
                        # client-secret: set in IntelliJ configuration
                        redirect-uri: "{baseUrl}/auth/login/oauth2/code/{registrationId}"
                        authorizationGrantType: authorization_code
                        clientName: Yandex
                #                    github:
                #                        # client-id: set in IntelliJ configuration
                #                        # client-secret: set in IntelliJ configuration
                #                        redirect-uri: "{baseUrl}/auth/login/oauth2/code/{registrationId}"
                #                        scope:
                #                            - user:email
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: sub
                    yandex:
                        authorization-uri: https://oauth.yandex.ru/authorize
                        token-uri: https://oauth.yandex.ru/token
                        user-info-uri: https://login.yandex.ru/info
                        user-name-attribute: id
#                    github:
#                        authorization-uri: https://github.com/login/oauth/authorize
#                        token-uri: https://github.com/login/oauth/access_token
#                        user-info-uri: https://api.github.com/user
#                        user-name-attribute: id